export const ActionTypes = {
	BASE_NOTIFICATION_SET: 'BASE_NOTIFICATION_SET',
	BASE_NOTIFICATION_CLEAR: 'BASE_NOTIFICATION_CLEAR',
	BASE_NOTIFICATION_LOADER: 'BASE_NOTIFICATION_LOADER',

	SAMPLE_DATA_LIST: 'SAMPLE_DATA_LIST',
	SAMPLE_DATA_DETAIL: 'SAMPLE_DATA_DETAIL',
};

export default ActionTypes;
